### ISSUE TITLE
Hugo template for the new site

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#1]
- [x] @nickelskevin please add @rocky to The @ Foundation GitHub site
- [x] @nickelskevin can you please add @intiserahmed to the Foundation site as well?
- [x] Start with research @rtilney @aannttoo 
- [x] Template look and feel draft @aannttoo 
- [x] Colors @rtilney

**Comment by ksanty** [comment]
Jory, are you able to help with this?

**Comment by rtilney** [comment]
Here are a few favorites for Hugo templates with a "docs" lean to them. These particular templates are documentation specific. 

I believe we still have to add a frontend (home page), but there are a lot of creative was to accomplish this while having a developer feel.

1. https://themes.gohugo.io/hugo-geekdoc/ (Simple and clean, light and dark mode)
2. https://themes.gohugo.io/docsy/ (basic, tried and true layout)
3. https://themes.gohugo.io/doks/ (favorite of the bunch, has a nice doc section and grid layouts)

**Comment by anthonyvprakash** [comment]
@rtilney  - I spent some time on the templates over the last couple of days, I agree with your list. Those are the best ones with the docs/dev feel to them - the github stars speak for them too.

Here are three additional ones to consider 
1. https://themes.gohugo.io/hugo-theme-learn/
2. https://gethugothemes.com/products/godocs-hugo-documentation-theme/ ( this one is paid though!)
3. https://themes.gohugo.io/theme/docuapi/?shell#introduction

**Comment by rtilney** [comment]
@aannttoo This is a great list as well. The paid theme ([GoDocs](https://gethugothemes.com/products/godocs-hugo-documentation-theme/)) is interesting and could potentially have better support and documentation. It's also Netlify Pre-Configured which means that there is most likely a CMS component which is great for non-technical content that isn't related to docs or code.

**Comment by ksanty** [comment]
https://hugoranked.com
