### ISSUE TITLE
Policy and Process

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/atsign.dev#10]
Short term scope - long term large task
- [x] define policy and process for atsign.dev @aannttoo @cpswan

**Comment by ksanty** [comment]
Denise can you help with this? @cconstab are you able to help with this?

**Comment by atsigndenise** [comment]
Yes.  I can help.  Does it make sense for me to start a google doc and bring in the Chris Article and the JDF Community Spec links.  And then, read and summarize them?  Please coach me on the initial tasks to get started.

**Comment by cpswan** [comment]
@atsigndenise the **policy and process** we're concerned with here is how stuff gets from idea to published (and maintained) on the new atsign.dev site. So I'm not sure the JDF stuff has much bearing on the topic.

**Comment by atsigndenise** [comment]
Understood.  How can I help?  Shall we start a document on "how stuff gets from idea to published to maintained?"  I could interview you then start/write a doc to get if off the ground.  Or, I can do some independent research.  Please let me know what is best and how I can help.  I'm a quick study, I just need a little coaching.  I'm super interested in this effort.  Thanks, Denise

**Comment by ksanty** [comment]
@atsigndenise is research and will collaborate with @cpswan
