### ISSUE TITLE
SEO Keywords inclusion across the site

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#110]
Barbara Lead

- [x] From the [master list of SEO](https://docs.google.com/spreadsheets/d/1U4NhpvYiEsGAyCGOqKAAYZBRR9jetNNeok1jiRw8l98/edit#gid=329975840) key words identified pick the ones that need to go into the new website
- [x] Include the keywords in the pages as appropriate

**Comment by tallent** [comment]
Here are [a list of suggestions](https://docs.google.com/document/d/1VY1Ui7UQ1pt2dBjBxsjerfV8DZ-h15Z2D48yam4bnMw/edit#heading=h.wth6vxka6rux) for review.
