### ISSUE TITLE
Document how to add content to the site

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#13]
- [x]  document on the site how to add to the site @TylerTrott 
- [x] Documentation should be on the site itself! @TylerTrott @aannttoo @cconstab

**Comment by TylerTrott** [comment]
Current documentation on how to add content to the site can be found within two separate articles:
[Working With Hugo (Static Webpage Generator)](https://docs.google.com/document/d/11avhw72reiJdKP6ybzbTnG4kZwkDR5SMlK4nYBICXJ4/edit?usp=sharing)

[Contributing to an Open-Source GitHub Project](https://docs.google.com/document/d/1n0Dy6_tKVwwU2cFOuhF-ow--PLxPIqx3vObT52IJHYc/edit?usp=sharing)

Status of articles:
Working With Hugo (Static Webpage Generator) --> Current Task
Contributing to an Open-Source GitHub Project --> Complete

**Comment by cpswan** [comment]
@TylerTrott it would be better to have the docs here in GitHub, or as part of the site itself (per second check box on the issue root)
