### ISSUE TITLE
Data Privacy - Broken Link

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#142]
For more information on how your application can create, update, or delete data, see the @Persistence Keystore Guide and the [@Protocol Verbs [link is broken]](http://devstaging.atsign.wtf/docs/resources/data-privacy-and-permissions/verbs)

And here:
For more information on how your application can create, update, or delete data, see the [@Persistence Keystore Guide](Persistence Keystore Guide) and the [@Protocol Verbs](http://devstaging.atsign.wtf/docs/resources/data-privacy-and-permissions/verbs).

**Comment by anthonyvprakash** [comment]
Fixed the link to point to the verbs page. Will be moved in the next PR.

**Comment by TylerTrott** [comment]
Approved and merged
