### ISSUE TITLE
Change DESS AWS guide from word document github content.

### ISSUE THREAD

**Issue by 64jantuma** [atsign-foundation/atsign.dev#165]
**Is this a request for Brand New Content?**
N

**If existing content, please link **
https://github.com/atsign-foundation/atsign.dev/tree/trunk/content/en/guides/dess-aws

**Where do you intend to use or post this content?**
News Article

**Who is the audience?**
Developers / Architects

**Additional context**
Update guide

**Comment by 64jantuma** [comment]
I will be work on this topic.

**Comment by xavierchanth** [comment]
Can this be closed now @64jantuma?

**Comment by 64jantuma** [comment]
All done this can be closed.
