### ISSUE TITLE
Instructions should include (I think) the way to include the submodule for docsy. 

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#195]
**Describe the bug**
When following the instructions in CONTRIBUTING.md the docsy submodule is not pulled down. Including the commands to pull down docsy and configure it might be useful.

**To Reproduce**
1. Follow Instructions in CONTRIBUTING.md
2. The edit in the instructions is actually tough to do without hugo/docsy in place 

**Expected behavior**
Pull the Docsy submodule on the clone operation in my case

`git clone --recurse-submodules https://github.com/cconstab/atsign.dev.git`

The instructions are then exactly the same but git gets upset with the SHA on the docsy directory..

What is the correct method to get Docsy up and working and keep git happy without breaking anything..?

```
cconstab@Liberator:/mnt/c/Users/colin/GitHub/atsign.dev$ git status
Refresh index: 100% (3098/3098), done.
On branch trunk
Your branch is up to date with 'origin/trunk'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   themes/at_docsy (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
cconstab@Liberator:/mnt/c/Users/colin/GitHub/atsign.dev$ git diff
diff --git a/themes/at_docsy b/themes/at_docsy
index 32ff732b..61efff14 160000
--- a/themes/at_docsy
+++ b/themes/at_docsy
@@ -1 +1 @@
-Subproject commit 32ff732bbc0b208718053737d6194380e3c12b5b
+Subproject commit 61efff14113499a8e5cbb6f8aee514f5bd5c8d88
cconstab@Liberator:/mnt/c/Users/colin/GitHub/atsign.dev$
```

**Useful stuff**
https://gist.github.com/gitaarik/8735255
https://unix.stackexchange.com/questions/214879/git-submodule-shows-new-commits-submodule-status-says-nothing-to-commit

But I was not clear if leaving out Docsy was intentional ?

Thanks

@cconstab

**Comment by cpswan** [comment]
The answer is to use `--recursive` rather than `--recurse-submodules`
