### ISSUE TITLE
New sitemap

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#21]
Sitemap with structure of the different pages needed for the website. We can take the existing ones from the current site and add gaps that exist today

please add @denise to this task.  Keywords and sitemap are tied and I want to make sure we are optimizing.  I can take a lead role on this if you would like

**Comment by anthonyvprakash** [comment]
[atsign 2.0 Proposed Sitemap.pdf](https://github.com/atsign-foundation/atsign.dev/files/6512761/atsign.2.0.Proposed.Sitemap.pdf)

**Comment by cpswan** [comment]
@aannttoo it would be cool to have this in [Mermaid](https://mermaid-js.github.io/mermaid/#/) so that it's more dynamic. We can generate SVGs from the Mermaid markup (like on @cconstab [GitHub Profile](https://github.com/cconstab))

**Comment by anthonyvprakash** [comment]
Thanks @cpswan  - Will look into it today.

**Comment by ksanty** [comment]
@aannttoo what are next steps?

**Comment by rtilney** [comment]
@ksanty I'm working on a design and will share a draft this afternoon. I'm using the sitemap and staging site as a reference.

**Comment by ksanty** [comment]
> @rtilney  I'm working on a design and will share a draft this afternoon. I'm using the sitemap and staging site as a reference.

TY!

**Comment by anthonyvprakash** [comment]
We will roll with the version we have now. Future iterations can be made as needed.
