### ISSUE TITLE
Developer getting started page/pages

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#239]
The getting started as it stands focuses on infr and setup of the dev env not the code itself..

- [x] Using the skeleton demonstrate a simple app
- [x] Words (content creation)
- [x] Samples
- [x] Examples
- [x] Video - draft of script for runtime has been completed **PR21**

**Comment by ksanty** [comment]
@TylerTrott can you please update status before our sprint tomorrow?  TY!

**Comment by TylerTrott** [comment]
@XavierChanth to record a walkthrough of the skeleton app, can be published either on YouTube or on atsign.dev or both.

**Comment by xavierchanth** [comment]
I'm currently working through some bugs with the at_app repo that have come up this week.

**Comment by cconstab** [comment]
Pushed back to backlog until we can get some more time.. But we need to pull together a new devs video..

Colin

**Comment by xavierchanth** [comment]
my at_app demo coming up tomorrow may turn out to be a good temporary video
