### ISSUE TITLE
FAQ/Places where folks get stuck setting up Flutter/Dart needs to be on the site..

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#240]
This document needs to be added (confirmed that they still exist on Windows)

https://docs.google.com/document/d/1SWANgscH3UuVmKnUGMO9TNUbPB03k7i69r6s4JDg_X8/edit

Need not be in this format !

**Comment by ksanty** [comment]
@TylerTrott can you please update status before our call tomorrow?  TY!
