### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev#245]
- [x] Showcase page - `@arrive` to `@rrive` -- I can't get to the right spot in the code to update this. I think we need @nickelskevin to help on this one, please. 
  - Reviewed the taxonomy doc, it is correct as @‎arrive
- [x] ["It is **provably** true that The @ Company cannot access your private information without your explicit permission."](https://atsign.dev/docs/faqs/about/) @XavierChanth  Can you tell me the edit here? Do I need to bold 'provably'? thx!
- [x] `at_virtual_enviroment` to `at_virtual_environment` [here](https://atsign.dev/docs/get-started/the-virtual-environment/#:~:text=Start%20up%20the%20at_virtual_enviroment) - This looks like it's been updated already, @XavierChanth

**Comment by XavierChanth** [comment]
- [ ] Showcase page - `@arrive` to `@rrive`
- [ ] ["It is **provably** true that The @ Company cannot access your private information without your explicit permission."](https://atsign.dev/docs/faqs/about/)

**Comment by ksanty** [comment]
Hi @XavierChanth making sure you know about the [empty character](https://emptycharacter.com) tool we use after @ signs.

**Comment by yahu1031** [comment]
This too `at_virtual_enviroment` to `at_virtual_environment` [here](https://atsign.dev/docs/get-started/the-virtual-environment/#:~:text=Start%20up%20the%20at_virtual_enviroment)

**Comment by xavierchanth** [comment]
Thanks :)

**Comment by jenmonroe** [comment]
> Hi @XavierChanth making sure you know about the [empty character](https://emptycharacter.com) tool we use after @ signs.

@ksanty I do not know about this! Sounds like I should?

**Comment by ksanty** [comment]
> > Hi @XavierChanth making sure you know about the [empty character](https://emptycharacter.com) tool we use after @ signs.
> 
> @ksanty I do not know about this! Sounds like I should?

@jenmonroe yes using the empty space character is perfect.  :). Thanks for being on top of it!!

@ksanty  Meant to follow up on this earlier -- I don't know what it is, and didn't want to do edits wrong. I get the use of it I think after looking at the page, but does it go after every @ sign, so like "@ jenmonroe(emptycharacterspace) is updating this page?" But with the unicode and not my note? :D
