### ISSUE TITLE
Customized New look and feel options for landing page based off of the Hugo themes

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#25]

**Comment by rtilney** [comment]
Are we confirmed with Docsy? This will be used as the basis for the design and layout.

**Comment by anthonyvprakash** [comment]
> Are we confirmed with Docsy? This will be used as the basis for the design and layout.

@rtilney  - that's the path we have been headed towards.

**Comment by anthonyvprakash** [comment]
https://www.docsy.dev/docs/examples/  - these are some sites on Docsy. The customized websites list give us a good view of what can be done.

**Comment by ksanty** [comment]
@aannttoo what are next steps here? Thanks!

**Comment by anthonyvprakash** [comment]
I think we are mostly leaning towards using Docsy with some of our own customization. Will close this out tomorrow on the website call.

**Comment by rtilney** [comment]
Hi all: Updated @platfom (formerly @dev) design draft based on "Docsy" theme and current sitemap. Contents TBD. https://xd.adobe.com/view/f8181f50-f288-4e59-99c5-b786dbfc5d66-ad4b/

**Comment by JoryDJD** [comment]
THanks, Rocky! We’ll review on the website call.


@jory

Jory Des Jardins
CMO
415.786.6126 | ***@***.*** ***@***.***>










 
 <https://atsign.com/>

**Comment by anthonyvprakash** [comment]
Rocky has a first iteration of the look and feel with which we will add to the WTF site.
