### ISSUE TITLE
Review and contribute to policy and process outline

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#26]
- [x] This pr12 dev sprint we would like dev and app dev teams to [review the outline](https://docs.google.com/document/d/1XSXgqIG7BDQUSxdrnyorCEzb6BJbB_l4Zb0Jp0ou1l4/edit) for contributing to open source, and start the process of contribution 

- [x] Use Flutter as a template for open source dev site contributions (@kevin -- please add the link)

**Comment by nickelskevin** [comment]
as usual - the flutter team provides a good example to learn from:

https://github.com/flutter/website/blob/master/CONTRIBUTING.md

Note: this is the outline. tons of content underneath....

**Comment by ksanty** [comment]
@cpswan @nickelskevin @cconstab @murali-shris @VJag @Sameeraja-Bharathula @aannttoo - please review the outline and provide input before Thursday am PST, IST and BST.  

https://docs.google.com/document/d/1XSXgqIG7BDQUSxdrnyorCEzb6BJbB_l4Zb0Jp0ou1l4/edit

**Comment by atsigndenise** [comment]
As a follow on to the above, here are more specific directions.  This is an overview outline of what will become two different docs:  (1) dev site and API policies and process and (2) overview to source code and licenses.  At this point, I just need you to look at this three page doc and see what you think needs to be added or comment on what you think might be an issue.  I think if you take 15 min to get your head around it, it will be worth your time and input.  Thanks, Denise
