### ISSUE TITLE
New Medium article on Getting started with the @ platform

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#279]
- [x] Prelude and context by @anthonyvprakash 
- [x] Getting started steps and code snippets by @XavierChanth
  - [x] at_app update to 1.1.0 - waiting testing from @cconstab to merge PR + publish
  - [x] chit_chat update to use at_app v1.1.0 - waiting for at_app 1.1.0 to be published
- [x] Review  & feedback by team
- [x] Publish by Oct 18

**Comment by xavierchanth** [comment]
The focus for the article has evolved to draw in flutter developers looking for a no backend platform to build upon.
I've estimated at about 3SPs.
