### ISSUE TITLE
On Site search

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#28]

**Comment by anthonyvprakash** [comment]
@nickelskevin  - Given that you mentioned that Docsy search was already working, do we want @TylerTrott and @Intiserahmed to do any further work on this task?

**Comment by ksanty** [comment]
@Intiserahmed @TylerTrott please provide and update.

**Comment by TylerTrott** [comment]
Kevin already implemented lunr.js as a way to search on the dev site. Lunr prevents needing to connect to an external server to search. Currently walking through steps of implementation of Algolia search and its potential benefits on atsign.dev @ksanty
