### ISSUE TITLE
Logos missing from Community page

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign.dev#283]
**Describe the bug**
Discord and YouTube logos are missing.

**To Reproduce**

Visit https://atsign.dev/community/

**Expected behavior**

All boxes have Logos

**Screenshots**
![image](https://user-images.githubusercontent.com/478926/136011824-4b995357-98cd-42ea-96af-b17d80ab6866.png)

![image](https://user-images.githubusercontent.com/478926/136011871-a6b6370b-994e-4cf6-9c3d-be3301e27a3a.png)

**Comment by harish127** [comment]
hey i can fix the issue..

**Comment by HimangsKalita** [comment]
I think I can do it

**Comment by itsdharmxd** [comment]
hey  **@cpswan**   assign me this i am working on this

**Comment by shikhar13012001** [comment]
I would love to work on this.  Could you assign this issue to me, if it is still open?

**Comment by TylerTrott** [comment]
Fix was pushed in most recent release.
