### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#29]
- [ ] Pick terms to optimize

**Comment by ksanty** [comment]
https://docs.google.com/spreadsheets/d/1U4NhpvYiEsGAyCGOqKAAYZBRR9jetNNeok1jiRw8l98/edit#gid=1352330191

**Comment by JoryDJD** [comment]
I've already started to go through Barbara's terms and highlighted some that look most promising to pursue. I'm glad to be on this task with Barbara, and I believe Denise has set up a meeting for us all to refine the list.

**Comment by ksanty** [comment]
@JoryDJD thanks for the update!

**Comment by ksanty** [comment]
@tallent @JoryDJD looks like the spreadsheet is updated. What are next steps?

https://docs.google.com/spreadsheets/d/1U4NhpvYiEsGAyCGOqKAAYZBRR9jetNNeok1jiRw8l98/edit#gid=1792217737

**Comment by atsigndenise** [comment]
In the Thoughts and Insights Tab, the 5-6 keywords for the dev site and com site have been highlighted. 
https://docs.google.com/spreadsheets/d/1U4NhpvYiEsGAyCGOqKAAYZBRR9jetNNeok1jiRw8l98/edit#gid=329975840
