### ISSUE TITLE
Content Migration from at_docsy to atsign.dev

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#295]
The Community page is built as an HTML file within the at_docsy repo. In order to use assets found in the static folder of atsign.dev, we will need to transfer the content found in the community-page.html in at_docsy to the community.md that resides in atsign.dev. 

This migration will need to be tested in a local environment and devstaging.

**Comment by RakeshPotnuru** [comment]
Hi @TylerTrott 
Is this issue resolved?

**Comment by TylerTrott** [comment]
> Hi @TylerTrott
> Is this issue resolved?

Hi there, yes this issue was resolved some time ago, but there is a similar raised issue that covers the migration to short code for every page if you’re interested!

**Comment by RakeshPotnuru** [comment]
@TylerTrott 
Yes, I am interested to work on that.
