### ISSUE TITLE
Getting Code and Apps ready for Hack Princeton

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#298]
- [ ] Content for presentation
- [ ] Chitchat code

**Comment by TylerTrott** [comment]
Thought we were gonna revamp at_hello_world or at_cookbook for Hack Princeton? @anthonyvprakash

**Comment by xavierchanth** [comment]
> Thought we were gonna revamp at_hello_world or at_cookbook for Hack Princeton? @anthonyvprakash

I thought so too, I am also working on a very simple todo list application which was intended as a demo application. I'm happy to go with whatever feels right for this crowd.

**Comment by anthonyvprakash** [comment]
That is totally your call on what we want to showcase as an easy app. The card is here to track it and make sure we don't miss the work.

**Comment by anthonyvprakash** [comment]
completed.
