### ISSUE TITLE
Decide on name and branding of site

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#30]
Both 
AtSign.Dev
Developer.AtSign.com

New Branding
At Platform

**Comment by nickelskevin** [comment]
So - options currently are between atsign.dev and atplatform.dev.

Any others?

**Comment by anthonyvprakash** [comment]
@atsigndenise  suggested atstack.dev

I also like at.dev ( but it says it was registered in 2019, was it one of ours? @cconstab )

**Comment by cpswan** [comment]
at.dev isn't ours

```
Domain Name: at.dev
Registry Domain ID: 323C95979-DEV
Registrar WHOIS Server: whois.google.com
Registrar URL: domains.google
Updated Date: 2021-04-10T01:14:52Z
Creation Date: 2019-02-24T01:14:52Z
Registry Expiry Date: 2022-02-24T01:14:52Z
Registrar: Google LLC.
Registrar IANA ID: 895
Registrar Abuse Contact Email: email@google.com
...
Name Server: ns-1292.awsdns-33.org
Name Server: ns-1658.awsdns-15.co.uk
Name Server: ns-360.awsdns-45.com
Name Server: ns-561.awsdns-06.net
```

Whilst the registrar is Google the awsdns name servers suggest that it's a Google customer account.

**Comment by JoryDJD** [comment]
I am partial to naming the site @platform, and using @dev to refer to our developer-facing programs: @certification and @affiliates. I would also add a qualifier to @dev so it's clear in our navigation: @dev Program. I've tweaked in the site map to show how it would appear in nav hierarchy.  I'm adding the discussion of these options to our Marketing Sprint.

**Comment by anthonyvprakash** [comment]
**New Options that we have to discuss :** 
atplatform.dev or .io
atstack.dev or .io
atdev.io
or stay with the current one

(whichever we pick, we should probably get the .org or .foundation as well)

Please add others.

**Comment by ksanty** [comment]
Hi all!  I think Jory would like to poll the team on their preference.  @JoryDJD shall we create a Google form and send to the team for a vote?  I'm just not clear on what all the options are.

**Comment by JoryDJD** [comment]
Kim if you could set this up and send to the team I would be SO appreciative!


@jory

Jory Des Jardins
CMO
415.786.6126 | ***@***.*** ***@***.***>










 
 <https://atsign.com/>

**Comment by anthonyvprakash** [comment]
As of May 27, I have 9 responses - 55% voted to keep the URL as atsign.dev - rest voted for developer.atsign.com.
