### ISSUE TITLE
Ongoing Enhancements of the dev site

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#315]
Notes of features, possible enhancements, etc.
_These are all optional (or potential) enhancements_

- [x] Click on infrastructure, privacy by design and rapid onboarding icons

- [x] Get Started button is far away

- [ ] A back and next button on the bottom of pages

- [ ] Center everything

- [ ] Add dartpad playground and example code (iFrame DartPad?)

- [ ] List of things to know to get better at it - w3schools

Basics to getting started
- Onboarding
- Creating objects
- Sharing objects
- etc.

- [ ] Cant tell where we are on nav bar left

- [ ] Too much reading — Read more here instead

- [ ] A quick start guide

- [ ] Product Roadmap

Reference websites: 
- https://shibatoken.com
- https://docs.snowbank.finance
- https://learnxinyminutes.com
- https://www.w3schools.com

- [ ] Pictures and videos of what code looks like
- [ ] Separate background packages (at_client, at_client_mobile, etc.) from frontend packages (at_onboarding, at_chat, etc.)
- [ ] Reduce noise and focus in content deep-dive - especially Libraries & Widgets pages

**Comment by TylerTrott** [comment]
Note : - 
- Adding another enhancement (Reduce noise and focus in content deep-dive)

**Comment by anthonyvprakash** [comment]
Closing this ticket since we have several new tickets for the Dev site
