### ISSUE TITLE
Footer Content -> Hyperlinks Broken

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#322]
The footer notes with Github, Twitter and Discord have broken hyperlinks as displayed below. These hyperlinks exist in Shortcode. Any thoughts @Intiserahmed ?

<img width="1439" alt="Screen Shot 2021-11-26 at 12 12 32 PM" src="https://user-images.githubusercontent.com/66637408/143626304-28c038a6-21a0-4ef6-95f6-10fe1324112e.png">

**Comment by yahu1031** [comment]
This issue is due to having tab spaces before the footer content in [`content/en/_index.html`](https://github.com/atsign-foundation/atsign.dev/blob/trunk/content/en/_index.html#L146-L159) page

```html
{{< blocks/section color="dark" >}}

{{% blocks/feature icon="fab fa-github" title="Contributions welcome!"  %}}
We do a [Pull Request](https://github.com/atsign-foundation) contributions workflow on **GitHub**. New people are always welcome!
{{% /blocks/feature %}}

{{% blocks/feature icon="fab fa-twitter" title="Follow us!"  %}}
Keep up on all the latest news,releases and more on [Twitter](http://twitter.com/atsigncompany).
{{% /blocks/feature %}}
{{% blocks/feature icon="fab fa-discord" title="Join us on Discord!"  %}}
[Join](https://discord.gg/55sHTQFxfz) 1250+ developers in our growing Community.
{{% /blocks/feature %}}

{{< /blocks/section >}}
```
