### ISSUE TITLE
Scrollbar in footer content

### ISSUE THREAD

**Issue by gcshisir** [atsign-foundation/atsign.dev#324]
**Describe the bug**
Scrollbar appeared in footer content which is unexpected I guess

**Screenshots**
![Screenshot from 2021-11-29 19-32-23](https://user-images.githubusercontent.com/55572721/143879568-aa62cca2-6feb-46bc-bf95-23210d2639aa.png)

**Expected behavior**
No scrollbar and text in multiple lines

**Browser:**
 - Chrome, Firefox

**Were you using an @‎application when the bug was found?**
  - No

**Additional context**
Device screen resolution: 1366x768 (HD)

**Comment by yahu1031** [comment]
Fix is #323

**Comment by gcshisir** [comment]
@yahu1031 thanks

**Comment by TylerTrott** [comment]
Closing as this issue has been resolved
