### ISSUE TITLE
Dev Site : @ platform Intro Videos

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#334]
New Intro Video on the @platform for the Homepage 
**Plan A** - with graphics and voice over @hakeemawbrey 
**Plan B** - Explainer video manual ( immediate)  w/ @cconstab and @nickelskevin

**Comment by xavierchanth** [comment]
Idea: Animated voice over of founders telling story

**Comment by TylerTrott** [comment]
- [x] Video w/ Kevin/Colin recorded
- [x] Long version (Completed Editing)
- [x] Short version (Completed Editing)
- [x] Upload short version on Vimeo @hakeemawbrey 
- [x] Upload long version on Youtube
- [x] Upload on dev site
