### ISSUE TITLE
Dev Site : Give it a try(parlor trick)

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#335]
Lead: @TylerTrott 

**Give it a try**
at_app, just the basics, refer to details separately
Need to show action at a distance -  (the parlor trick, leverage web)
- Snack bar demo
- Light mode / dark mode

**Comment by cconstab** [comment]
Next set of actions

- [x] Add light/dark mode toggle to demo (@cconstab working on it but as a secondary issue) - Not going to be done
- [x] Convert application to template for at_app (@cconstab)
- [x] Flow mock up for page and get agreement (@TylerTrott)
- [x] Write narrative to go along with examples (@TylerTrott  but ask @cconstab / @nickelskevin if you need help!)

**Comment by TylerTrott** [comment]
Step-by-step written process completed. 
Video running through the steps in progress of being recorded/edited
