### ISSUE TITLE
Sitemap needs to be consolidated (too many nav items)

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/atsign.dev#34]
**Describe the bug**
The Sitemap needs to be consolidated or reorganized into subpages because it creates too many navigation  items

**To Reproduce**
1. First go to https://devstaging.atsign.wtf
2. Observe the top level nav
3. Notice too man items and overcrowded

**Expected behavior**
Should be clear and concise nav set.

**Screenshots**
<img width="1652" alt="Screen Shot 2021-05-20 at 7 37 55 PM" src="https://user-images.githubusercontent.com/1827777/119074044-2797ce00-b9a3-11eb-8517-1fe224e56297.png">

**Smartphone (please complete the following information):**
 - Device: MacBook Pro (15-inch, 2018)
 - OS: MacOS 11.3.1 (20E241)
 - Browser: Chrome
 - Version 90.0.4430.212 (Official Build) (x86_64)

**Were you using an @application when the bug was found?**
 - No

**Additional context**

**Comment by atsigndenise** [comment]
Hi.  We had tentatively come up with this top level nav in our meeting yesterday.  It pretty much follows what Flutter does and consolidated other areas under these top level ones.  https://docs.google.com/spreadsheets/d/1lFNZ_4laqjGVQkvmP6JjX1A3fCeEwSC2Ean7Ii63WYs/edit#gid=0

**Comment by atsigndenise** [comment]
There is a tentative site map as well showing the consolidation.  Anthony -- Can you share the sitemap?

**Comment by nickelskevin** [comment]
> There is a tentative site map as well showing the consolidation. Anthony -- Can you share the sitemap?

You can see it in the [source tree](https://github.com/atsign-foundation/atsign.dev/tree/trunk/content/en) (note the subdirectories). 

We can organize the page structure really easily once the nav and sitemap are reconciled.

**Comment by nickelskevin** [comment]
> There is a tentative site map as well showing the consolidation. Anthony -- Can you share the sitemap?

Is it [this doc](https://docs.google.com/spreadsheets/d/1VSsAdkIkpKsiXqBdk4v8nQUrwDwiQsrzDFVrQOJCmVg/edit#gid=0)?

**Comment by atsigndenise** [comment]
Found it:  https://drive.mindmup.com/map/1wwzyyhCrJd53F6cBDaLH442qLkIHi1_5

**Comment by JoryDJD** [comment]
I've pasted the map here directly if that helps. Please note that the "Github" link is meant to me a small Github icon with a star in it, not the actual word, Github. The yellow tabs are the landing page links at the top.
![image](https://user-images.githubusercontent.com/73364927/119076211-033df080-b9a7-11eb-8226-b9467424b9e8.png)

**Comment by nickelskevin** [comment]
Need to add Language selection to above, will check out how to move the Releases menu to the Documentation page.
Will removing GitHub cause accessibility issues?

**Comment by nickelskevin** [comment]
I checked in some changes:

- Removed about page
- Changed Documentation title to Docs
- Removed release menu for now, will figure out how to add to Documentation page

**Comment by anthonyvprakash** [comment]
@nickelskevin  - can we close this one for now, am sure we will iterate more on the top menu as we progress further.

**Comment by anthonyvprakash** [comment]
Closing this issue after discussing with @nickelskevin
