### ISSUE TITLE
Dev Site : Docs Sections Missing Documentation

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#341]
Lead: @TylerTrott 

**Misc items:**
- [x] Remove pricing it has its own section on the nav
- [ ] Remove the rSDK and just talk about the SDK  - we need brand new documentation to talk about the various elements of the new SDK and explanation of each component.
- [x] Take our other content that does not fit in the new flow

**Content needed on the following pages:**
- [x] chit_chat, @mosphere pro, wavi.ng
- [x] Data Architecture, Polymorphism
- [x] Dart and Flutter Packages Script no longer pulling content from pub.dev @cpswan 
- [x] Overall Core SDK documentation needed @kalluriramkumar @VJag 
- [ ] New Getting Started documentation

**Comment by cpswan** [comment]
@anthonyvprakash I can see that the UpdateLibraries workflow is running daily, and just not picking up any changes from pub.dev that need to be added to atsign.dev

The last time it did pick up a change and generate a Pull Request was 16 Dec.

What are you expecting to see that's not happening?

**Comment by TylerTrott** [comment]
Overall Core SDK documentation needed @kalluriramkumar @VJag
Documentation on the use cases of the SDK:
- [x] How to create keys
- [x] How to put, get, delete
- [x] How sharing works
- [x] Notifications
- [x] All services/managers (AtClientManager, Sync manager, notifcation manager)

**Comment by Intiserahmed** [comment]
Can we please include all the documentation at this [doc](https://docs.google.com/document/d/1RyoXsqFm99yVSWb0IlksUVsKmES4GLmPOA9AnMZXU7Q/edit#heading=h.j7t1yv3f93cr) . Thank you.

**Comment by VJag** [comment]
Sneak peek. Working on the docs for the following outlined items. Things might change, but just to give you a heads up.

All of the below content is related to "How to create keys" / "Different keys in At protocol"

Key basics:
 - Structure of a key
 - What is a valid key

public key

 - What is a public key
 - Creating a public key
 - Making public keys cacheable
 - Self-signing

shared key

 - What is the shared key
 - Creating a shared key
 - Polymorphic behavior of shared keys
 - Making shared keys cacheable
 - Encryption
 - Auto notification of the shared keys


self key

 - What is self key
 - Creating a self key
 - Encryption of the self keys


Key metadata attributes:

Time To Live:
Time To Birth:
CCD:
Time TO Refresh:


Lookup behavior for the keys with TTL and TTB

**Comment by VJag** [comment]
Outline for "How to put, get, delete"

 put() 

 - Explain the signature
 	- Arguments
 	- Return types
 	- Exceptions ~~ what can go wrong
 - What it does (Use dart docs)
   - Writing to localSecondary
   - Writing to remoteSecondary



 get() 

 - Explain the signature
 	- Arguments
 	- Return types
 	- Exceptions ~~ what can go wrong
  - What it does (Use dart docs)
  - various look up's
  - what can go wrong in a get


  delete()

  - Explain the signature
 	- Arguments
 	- Return types
 	- Exceptions ~~ what can go wrong
  - What it does (Use dart docs)

**Comment by VJag** [comment]
Notifications

- What is a notification
- Types of notifications
	- key
	- Text
- How to send a notification
	- Explain the signature
- Knowing if the notification is successful

**Comment by xavierchanth** [comment]
This all looks really good so far @VJag!

**Comment by Intiserahmed** [comment]
Instead of the whole Core SDK Documentation that we did,  We will work to create documentation on [these](https://atsign.dev/docs/get-started/understand-the-platform/namespaces/#:~:text=Try%20the%20%40platform-,Understand%20the%20%40platform,-Namespace) four point.

**Comment by ksanty** [comment]
@Intiserahmed what is your recommendation to complete this?  I know you will be taking leave soon.  What is left to do on this issue?  Thanks!

**Comment by VJag** [comment]
I believe a lot of documentation that many of us produced in the past is available in various folders in the shared drive.

For example:

architecture folder (https://drive.google.com/drive/u/1/folders/1md4LK-fxITBsCfDOMkIFhIE_ae5cJKYh)
documentation folder(https://drive.google.com/drive/u/1/folders/1O9bVrGwfgwsAxQU75IDMvuLXCGDoRh2q)

Can we take a day or two and index these documents and tag them with what they are then many of the things can be searched and reused. On the subjects like "encryption", I believe there must be whitepapers and powerpoints produced by us in the past.

**Comment by Intiserahmed** [comment]
@ksanty I will gatther and collect all the information from the previous sources. As I didn't know some of the similar document exist  , I will try to gather them in one place. I will try to finish this by this week. Thank you.

**Comment by xavierchanth** [comment]
Taking over for Intiser in PR35.

**Comment by cpswan** [comment]
@XavierChanth is this overtaken by events with the work on devsite 3, and if so can it be closed?

**Comment by xavierchanth** [comment]
Yes, it is replaced by: [atsign.dev-3.0#16](https://github.com/atsign-foundation/atsign.dev-3.0/issues/16)
