### ISSUE TITLE
Change the Java recommendation 16 to 8

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/atsign.dev#358]
**Is this a request for Brand New Content?**
Yes

**If existing content, please link **
[Java recommendation](https://atsign.dev/docs/faqs/flutter/#flutter-doctor-says-that-java-needs-to-be-installed)

**Depth/Length of content**
Any restrictions? No

**Who is the audience?**
Developers

**Additional context**
Please recommend using Java 8 instead of Java 16.

Here is the link
<https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=All&field_architecture_target_id=391&field_java_package_target_id=396>

**Comment by TylerTrott** [comment]
Edit made, cheers @yahu1031
