### ISSUE TITLE
Feb-Mar 2022 Traction

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#370]
8000 goal for February and March
Lead: @anthonyvprakash 

- [x] Identity possible participation across events and decide which ones to participate in
- [x] Campaign design/creation and roll-out for each of the events
- [x] Execution of campaigns

**Comment by ksanty** [comment]
[Daily Tracker](https://docs.google.com/spreadsheets/d/1PeubRwB7jA_fvVi7r3G8VgEBZ7IcVEyh69fIVLtqjE4/edit?pli=1#gid=270854702). 

- [x] Wk 1 - 2/1 (888) actual 1286
- [x] Wk 2 - 2/7 (888) actual 1433
- [x] Wk 3 - 2/14 (888) actual 1428
- [x] Wk 4 - 2/21 (888) actual 1873
- [x] Wk 5 - 2/28 (888) actual 2639
- [x] Wk 6 - 3/7 (888) actual 318
- [x] Wk 7 - 3/14 (888) actual 0
- [x] Wk 8 - 3/21 (888) actual 50
- [x] Wk 9 - 3/28 (888) as of 3/24 129 (Total 9156)
