### ISSUE TITLE
AtSign.Dev Edits | Suggestions by KimS + JenM

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#373]
Page: http://devstaging.atsign.wtf/docs/get-started/ 

- [x] Feel like we need a general suggestions email alias embedded to all the docsy pages, so we can capture comments/suggestion on any page (under what is the atplatform)

Page: http://devstaging.atsign.wtf/docs/get-started/tryatplatform/
- [x] Suggested language change #374 
- [x] Flow was difficult for me to follow, but I'm not a developer.  Let's see if @jenmonroe feels the same.  Maybe its the 2 columns and the floating right hand bar. @jenmonroe says: Maybe something like: The directions in the left-hand column below will guide you through setting up an application that utilizes the @platform to send simple data. Watch the Receiver display in the right-hand column to see the sent data. 
- [x] Update Seeing the @platform in action to Watch the ... to keep in line with other titles used #376 

Page: http://devstaging.atsign.wtf/docs/sample_apps/snackbar/
- [x] Should this text have added to it, the opportunity to practice with our tech? _SnackBar is a simple end-to-end encrypted application that allows for securely sending snacks (chocolate bars!) to a receiving @sign. Below is the step-by-step process that will assist you in getting the SnackBar application up and running._
- [x] Should we add a link to at_app? _You are able to download application templates from our at_app project! Copy and paste the following code in your terminal to activate **at_app** on your machine:_
- [x] Should we bold important steps to highlight what someone might miss?  For example: Please complete these steps before continuing.
![image](https://user-images.githubusercontent.com/74563278/150204062-dc66df0c-388f-46fa-99a4-5a12a850dcb5.png)

**Comment by xavierchanth** [comment]
Alternative solutions to an email alias:
- Link to a google form - Could automate this to automatically create an issue for us.
- Link to open a new issue on the repo

**Comment by TylerTrott** [comment]
All items in issue have been resolved. Thank you for feedback!
