### ISSUE TITLE
Integrate Rocky's design into Docsy WTF site

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#38]
Intiser to lead - Anthony and Tyler to support

Context: Take new assets, CSS files and designs and integrate with Docsy pages.

1. Homepage

- [x] Background
- [x] Github Button add
- [x] Customize button
- [x] Vertical Cards section
- [x] Horizontal Cards section
- [x] Divider 
- [x] Video Embed
- [ ] Notification and announcement section

2. DocPage

- [x] Add search to doc page only
- [x] Customize search outlook
- [x] Change color to company theme  color
- [x] Collapse Functionality 

3. ShowcasePage

- [x] Add short background 
- [x] Showcase cards
- [x] Learn  more button

4. Navigation bar
- [x] Add github and discord button 
- [x] change the color to white when the logo is ready.
- [ ]  Status underline bar

5. Footer

- [x] Add main menu

**Comment by cpswan** [comment]
@rtilney are you able to make a pull request for your theme customisations into this repo?

**Comment by rtilney** [comment]
@cpswan I don't know the procedure for this. My designs are static XD files.

**Comment by cpswan** [comment]
@rtilney - so the walkthrough we did a few days back was an XD mockup rather than a customised version of Docsy?

If that's the case then we have much more work to do than I thought when we were in the sprint planning, because somebody (who?) needs to implement the design as a customised Docsy theme.

**Comment by rtilney** [comment]
@cpswan Correct. Sitemap, design, and implementation are all separate tasks. I can provide the assets. ie: hex codes, fonts, heading tags, icons, etc...and the static design reference.

**Comment by Intiserahmed** [comment]
@rtilney Yeahh can you please share all the assets?

**Comment by rtilney** [comment]
@Intiserahmed Here is the developer XD link. https://xd.adobe.com/view/f8181f50-f288-4e59-99c5-b786dbfc5d66-ad4b/

**Comment by anthonyvprakash** [comment]
The latest on this - @Intiserahmed has done some of the styling changes but yet to integrate into the WTF site.

**Comment by ksanty** [comment]
@Intiserahmed can you please determine next steps and add to the issue card?  @aannttoo and I added context to the card for the team.  Thank you!

**Comment by Intiserahmed** [comment]
@ksanty sure done!

**Comment by ksanty** [comment]
> @ksanty sure done!

Fantastic!  Super helpful @Intiserahmed.  Thank you!
