### ISSUE TITLE
Flutter Silicon Valley

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#390]
Lead : @anthonyvprakash 

- [x] Launch on Twitter
- [x] Promotions
- [x] Decide on date for first meetup
- [x] Finalize location, logistics
- [x] Marketing
- [x] Lock down agenda and speakers

**Comment by xavierchanth** [comment]
The [flame team](https://flame-engine.org) has been very active, they did a talk at Flutter Toronto & Flutter Vikings, might be good to reach out to them.
