### ISSUE TITLE
Build broken: failed to extract shortcode: template for shortcode "features" not found

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign.dev#392]
**Describe the bug**

#386 uses a shortcode "features" but seems to be missing the code (or template revisions) that introduce it.

The build GitHub Action is failing:

```
Run hugo --minify
  hugo --minify
  shell: /usr/bin/bash -e {0}
Start building sites … 
WARN [2](https://github.com/atsign-foundation/atsign.dev/runs/5046657183?check_suite_focus=true#step:8:2)022/02/0[3](https://github.com/atsign-foundation/atsign.dev/runs/5046657183?check_suite_focus=true#step:8:3) 03:[4](https://github.com/atsign-foundation/atsign.dev/runs/5046657183?check_suite_focus=true#step:8:4)2:[5](https://github.com/atsign-foundation/atsign.dev/runs/5046657183?check_suite_focus=true#step:8:5)[6](https://github.com/atsign-foundation/atsign.dev/runs/5046657183?check_suite_focus=true#step:8:6) Content directory "/home/runner/work/atsign.dev/atsign.dev/content/en/docs/Archives/guides" have both index.* and _index.* files, pick one.
Error: Error building site: "/home/runner/work/atsign.dev/atsign.dev/content/en/_index.html:54:3": failed to extract shortcode: template for shortcode "features" not found
Total in 182 ms
```

**To Reproduce**
1. cd into a recent clone of this repo (or `git pull` on `trunk` for an existing clone
2. run `hugo server`
3. `Error: Error building site:`...`failed to extract shortcode: template for shortcode "features" not found`

**Expected behavior**
Site builds

**Additional context**

@Intiserahmed you created #386 so maybe you have a local change (to the at_docsy template?) that's needed to make it work.

**Comment by xavierchanth** [comment]
This is what happens when the at_docsy ref hasn't been updated in atsign.dev but the shortcodes from at_docsy are being used.

**Comment by Intiserahmed** [comment]
Yeap from now on will make sure the at_docsy pr merged first then make a pr in the atsign.dev

**Comment by xavierchanth** [comment]
Same type of situation with the build that just failed this morning:
The submodule ref has been updated in atsign.dev, but hasn't been pushed to at_docsy yet.

**Comment by TylerTrott** [comment]
Build works now, issue was atsign.dev repo was pushed first and pointing at a previous push rather than the most up-to-date at_docsy. Note: Push and merge at_docsy pr's first and then point atsign.dev to merged at_docsy.
