### ISSUE TITLE
Electrothon 4 (Feb 18 - 20)

### ISSUE THREAD

**Issue by knowShubhangi** [atsign-foundation/atsign.dev#398]
1. Event Type: Hackathon
2. Website: https://electrothon.specnith.com
3. Expected participants: 2000
4. atsigns expected : 1500

Activities :
- [x] Meme Contest
- [x] Session on @ platfrom
- [x] Tshirt Giveaway

**Comment by ksanty** [comment]
@Shubhangi0304 thanks for adding context to the event.

**Comment by anthonyvprakash** [comment]
T-shirt winners and logistics pending - updated Sprint points

**Comment by anthonyvprakash** [comment]
All activities completed.
