### ISSUE TITLE
JIIT (March 4 - 6)

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#403]
Lead : @Shubhangi0304  & @Jatinpandya26 

Event Type: Hackathon
Website: https://gdscjiit128.tech/#/bitbox
Expected participants: 300
atsigns expected : 300

- [x]  At Sign Campaign
- [x]  Logistics of t-shirt shipping

**Comment by knowShubhangi** [comment]
everything is ready to go, waiting fo the hack to start
