### ISSUE TITLE
Landing page design for each of main category pages in the top menu

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#41]
Rocky Lead

XD Prototype: https://xd.adobe.com/view/f8181f50-f288-4e59-99c5-b786dbfc5d66-ad4b/

**Comment by rtilney** [comment]
- [ ] determine content for each page
- [ ] create designs/layouts for each page
- [ ] share designs with team/get feedback
- [ ] revise and finalize
