### ISSUE TITLE
Mobile View- Landing Page - Icons not centered

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#426]
*What the issue is* 
The icons that exist under the section, 'New to the @ platform', are not entered on mobile view

*How to resolve issue*
Center the icons

**Comment by Rohitrout416** [comment]
Hi I would like to work on this issue. Please assign me.

**Comment by vermaayush680** [comment]
Hi @TylerTrott,
I can fix this issue.
The problem is that the parent div is relative and it is affecting the icons.
Also, there is a lot of extra space after each image because of the unused margin in the featurette-divider.
If you can assign the issue to me, I can fix it.

**Comment by vardhinii** [comment]
Hey! @TylerTrott, I would like to work on this issue

**Comment by Rohitrout416** [comment]
Hey I tried to fix the issue [here](https://github.com/atsign-foundation/atsign.dev/pull/438). Please check it.

**Comment by yahu1031** [comment]
@vermaayush680 Has resolved this issue with PR #439
