### ISSUE TITLE
Mobile View- Landing Page - EFF/GEC logos

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#427]
*What the issue is*
The logos for EFF and GEC on mobile view are cut off and do not flex appropriately.

*How to resolve issue*
Allow logos to flex with changing height & width ratios

**Comment by Sandhya312** [comment]
Hey @TylerTrott, I am a contributor to openforce'22. I want to work on this issue. Please assign this issue to me.

**Comment by TylerTrott** [comment]
This issue has been resolved. Thank you for your contributions!
