### ISSUE TITLE
Privacy Page under Docs is empty

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#428]
*What the issue is*
Our Privacy page that exists within our Docs section is currently blank.

*How to resolve this issue*
- We can migrate this file to our 'Archives' folder until we have time to fill it with content.
- We can add relevant content to the file.

**Comment by Swastyy** [comment]
Hi @TylerTrott , I want to contribute to this issue. Please assign. Thanks.

**Comment by TylerTrott** [comment]
@Swastyy has resolved this issue.
