### ISSUE TITLE
Landing pages design, content and messaging

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#43]
Hakeem Lead - Next Steps:
- [ ] Get review & inputs on [home page content](https://docs.google.com/document/d/1fPBDcBLJ1roSUSqCKKodEYZurk9okUZQnewjLnN5Elw/edit?ts=60b902ef)
- [ ] Import Content to new Docsy template
- [ ] Review above Docsy template with team
- [ ] https://github.com/atsign-foundation/atsign.dev/issues/43#issuecomment-854010663 
- [ ] https://github.com/atsign-foundation/atsign.dev/issues/43#issuecomment-853499034
- [ ][ Tied to issue](https://github.com/atsign-foundation/atsign.dev/issues/59)

**Comment by hakeemawbrey** [comment]
https://docs.google.com/document/d/1fPBDcBLJ1roSUSqCKKodEYZurk9okUZQnewjLnN5Elw/edit?hl=en&forcehl=1

I have created this document for organization of the front page.

It contains existing content from our current dev site + more sections for our needs. Please add suggestions/edits

Next steps would be to import this content on to the new staging dev site, then edit the content and design again.

**Comment by hakeemawbrey** [comment]
**Clear Needs for the dev site**
Reflected in Hakeem's homepage doc
- [ ] Salient features
- [ ] Differentiators
- [ ] Call to action
- [ ] App showcase etc

**Comment by hakeemawbrey** [comment]
Next Steps:

- [x] Get review & inputs on home page content
- [ ] Import Content to Adobe XD Mockup
- [ ] Review Mockup with team

**Comment by ksanty** [comment]
@hakeemawbrey can you please add next steps for this task?

**Comment by ksanty** [comment]
Can everyone review @hakeemawbrey homepage content doc and add notes please?  Thanks!

**Comment by eskao654** [comment]
https://docs.google.com/spreadsheets/d/1VSsAdkIkpKsiXqBdk4v8nQUrwDwiQsrzDFVrQOJCmVg/edit?usp=sharing list of all pages that will be on the dev site

**Comment by hakeemawbrey** [comment]
Update on website homepage content 


- [x] I believe @Intiserahmed has successfully ported over into Hugo Rocky design template 

- [x] Had content call meeting 6/8 regarding homepage content. Over all message everything needs to be simplified & adjusted based on our target audience 

- [x]  Had successful jamboard 6/11 regarding narrowing dev target audience, need to narrow down more
https://jamboard.google.com/d/1rO1VJNDfj_3bl3Bj9Yg2VB_iDJya3Me3ldOxDCZGp4w/viewer?f=0

- [ ] Follow up jamboard question
https://docs.google.com/document/d/1RYKgMZtujO21Mo5OrY9WxdvxvFbniPRpvM5RSwm78Os/edit



**Basic needs for website** 

- [ ] - Hero copy, tag line, + CTA (get started)
- [ ] - Defining characteristics/features of @ platform 
- [ ] - Dev program

**Comment by hakeemawbrey** [comment]
Next steps
- [ ] use new messaging based on target demo 
**What is the @ platform**
https://docs.google.com/document/d/17PClBSTnaWJpBgsXEd8DaWD54wbi85QsRgGZSozJI7c/edit

- [ ] Set in stone the defining characteristics that are attractive to our target demo
- [ ] Implement @jenmonroe Dev program content
https://docs.google.com/document/d/143s3gOS9_dSJzEA0IU5aieZEIras0Wfuzn1DkcabO2c/edit
- [ ] Implement basic pages/site map for @eskao654 document https://docs.google.com/spreadsheets/d/1VSsAdkIkpKsiXqBdk4v8nQUrwDwiQsrzDFVrQOJCmVg/edit#gid=0
