### ISSUE TITLE
Landing Page - Icons

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/atsign.dev#432]
*What the issue is*
We currently only have one clickable icon on the landing page - join our developer community. Let's try to reimagine ways in which we can properly utilize these icons.

**Comment by vermaayush680** [comment]
Hi @TylerTrott, 
I can work on this issue as well.
But would like to know, where do you want the other icons to redirect to?
I believe all of them should redirect to the developer community page but would like to confirm before I get assigned.

**Comment by TylerTrott** [comment]
@vermaayush680 this is a good questions. We should have them link to relevant places within our site. We discuss infrastructure, privacy and rapid onboarding in the top three icons. We should be linking to relevant sources on the site for these. We used to have a Developer Highlight corner page but this was archived. I'd say link that to the community page as well. Thanks!

**Comment by hi-anusha** [comment]
"Hi, I am Anusha, a contributor to OpenForce 2022. I would like to work on this issue.Also please assign this issue to me. I cloned your repository and since there are many folders I would like to know which file or folder should I open to work on this issue? Thanks
