### ISSUE TITLE
broken link in Contributing guidelines

### ISSUE THREAD

**Issue by Rushijaviya** [atsign-foundation/atsign.dev#433]
In the contribution guidelines (CONTRIBUTING.md) in step 1 of Development Environment Setup which is Local Hugo Installation, the link of Working With Hugo is broken. When I click on it shows Error 404 webpage is not found. 

![image](https://user-images.githubusercontent.com/59735978/156634447-271215ae-2239-400c-8c01-3710d9189538.png)

As you can see in the above image. seeing URL I see that you have added the wrong URL for file getting-started-with-hugo.md. As you have added getting-started-with-hugo.md file in overview folder of docs.

I am going through the GitHub repo of atsign foundation and I found this. I am a participant in the OpenForce program. Can you assign this issue to me under it's tag?

**Comment by TylerTrott** [comment]
Hi there, I pushed this fix yesterday! You should see the updated site now.

**Comment by Rushijaviya** [comment]
> Hi there, I pushed this fix yesterday! You should see the updated site now.

You can see here [CONTRIBUTING.md](https://github.com/atsign-foundation/atsign.dev/blob/trunk/CONTRIBUTING.md). In this file when I click on [Working With Hugo](https://github.com/atsign-foundation/atsign.dev/blob/trunk/content/en/docs/guides/getting-started-with-hugo.md) in step 1 it shows the page is not found.
