### ISSUE TITLE
Showcase doesn't render correctly in desktop

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/atsign.dev#435]
**Describe the bug**
Footer is being hidden(looks like) due to the showcase cards.

**Screenshots**

https://user-images.githubusercontent.com/35523357/156650594-53c40beb-0b0b-4403-a987-2067ea5e4a7c.mp4

**Smartphone (please complete the following information):**
 - Browser: edge
 - Version: 98.0.1108.62

*How to resolve this*
 - Fix with shortcode
 - Format proper CSS
 - Related Issue #421

**Comment by amanbedi1** [comment]
Can you assign it to me I can do it

**Comment by TylerTrott** [comment]
> Can you assign it to me I can do it

Assigned

**Comment by vermaayush680** [comment]
Hi @TylerTrott can you assign it to me.
I have found the issue and would like to work on it.

**Comment by Bikramjit21** [comment]
Can anyone assign me?

**Comment by vermaayush680** [comment]
Hi @TylerTrott,
Fixed the Showcase footer issue.
Let me know if it's fine and I'll make a PR for it.
https://user-images.githubusercontent.com/42459801/157077485-9b19b7e5-3f42-4bef-8867-135eefb62e6c.mp4

Also here is the mobile view
https://user-images.githubusercontent.com/42459801/157078130-56f8688b-1103-476b-9d3b-34625024b254.mp4
