### ISSUE TITLE
showcase footer has white space at the edges.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/atsign.dev#447]
**Describe the bug**
The showcase footer has white space to the horizontal edges.

**To Reproduce**
Head over to [devstating showcase](http://devstaging.atsign.wtf/showcase/)

**Expected behavior**
It must fill those white space

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/157675708-1338402e-2e9b-44d5-89e7-93522eeff31d.png)

**Smartphone (please complete the following information):**
 - Browser Edge
 - Version 59

**Additional context**
Fix of https://github.com/atsign-foundation/atsign.dev/issues/435 lead to this.

**Comment by SarveshLimaye** [comment]
@yahu1031  Hi, I am Sarvesh Limaye, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

**Comment by vermaayush680** [comment]
@yahu1031 can you assign me with this issue? I would love to work on it

**Comment by nik132-eng** [comment]
Hi, I am Nikunj Rohit, a contributor to OpenForce 2022. If this issue is still open I would like to work on this issue and try better to enhance it more. I would be making a PR as soon as I am done with resolving the issue. Thank you
@yahu1031

**Comment by vermaayush680** [comment]
@yahu1031 I believe #448 fixes this issue

**Comment by nik132-eng** [comment]
@vermaayush680  are you sure ?? Because I am completely new and learning these things how to solve bugs and all.
