### ISSUE TITLE
Update Nomenclature on Pub.dev and other pages

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#45]
Tyler Lead:

Dependency on consolidating nomanclature docs

- [x] PR12.5 decide on which url's to migrate to new site - Refer to https://github.com/atsign-foundation/atsign.dev/issues/9
- [x] Update content on URL's (may fall to next sprint unless people can update real time as they are going through pages)

**Comment by ksanty** [comment]
@jenmonroe did I hear you mention you'd like to help on this task?  :)

**Comment by jenmonroe** [comment]
Sure I can help!

**Comment by ksanty** [comment]
> Sure I can help!

Ok cool, I'm going to take a stab at consolidating the 3 docs this weekend, so we have something ready for the Marketing sprint on Monday.
