### ISSUE TITLE
Open Source Policies & Processes

### ISSUE THREAD

**Issue by atsigndenise** [atsign-foundation/atsign.dev#46]
Denise Lead

- [x] Resolve review comments @cpswan 
- [x] Write section based on Flutter model @atsigndenise 
- [x] Review/edit section 
- [x] Determine Schedule for Completion @atsigndenise

**Comment by atsigndenise** [comment]
Deliverables for this week have been completed.  I did not have Esther review yet as I need to get further into the doc.  I'd like to get the Policies and Processes completed by June 15.

**Comment by ksanty** [comment]
@atsigndenise  I removed the callout for @eskao654.  I think the whole team can help here, so it doesn't all fall on Esther.  She's pretty slammed right now. :)

**Comment by athandle** [comment]
@ksanty I think you want to tag @atsigndenise

**Comment by ksanty** [comment]
> @ksanty I think you want to tag @atsigndenise

You're right!  :)
