### ISSUE TITLE
IoMT Pitch Deck :  Competitor Analysis

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#462]
- [ ] Industry analysis of current players in the IoMT
- [ ] T@C Positioning amongst the competition

**Comment by atsigndenise** [comment]
I can help out by identifying the leading analyst/research organizations in which to distill market research. For example, Mayo Clinic has a analyst division and possibly the Omdia group, who attended the Embedded IoT conference.  Will scout it out.
