### ISSUE TITLE
IoMT Pitch Deck : Target Markets Data

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#466]
Pitch Deck [link]( https://docs.google.com/presentation/d/1LJWN55BwP-2FpSYGk4ToHpwB8Mkmmco-O6EQ1IQnB14/edit#slide=id.g114c779c41c_0_62)

**Slide 6:** 

Find data about target markets over time 

-all people, all devices, and their data
- 2030
- We will be protecting everyone and everything

**Comment by hakeemawbrey** [comment]
"“Number of Connected IoT Devices Will Surge from 27 billion in 2017 to 125 Billion by 2030, IHS Markit Says"
https://news.ihsmarkit.com/prviewer/release_only/slug/number-connected-iot-devices-will-surge-125-billion-2030-ihs-markit-says

still only finding research on connect IoT devices. Still need to do more research on people in 2030 to combine with things.
