### ISSUE TITLE
@mosphere Pro Public Launch

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#471]
Repurposing the Engifest ticket for the AtPro Launch

- [x] Get Ok via decision log to move forward
- [x] Prep all external-facing content on AtPro
- [x] Banners (draft of ideas [here](https://docs.google.com/document/d/1KgG4TJAeE6EeYRGRSvfmMlylrGeB9gq59_Ut-320Gnk/edit)
- [x] Tracking and monitoring downloads and activation - ongoing
- [x] Post AtPro on Product Hunt
- [x] Launch Tuesday 5/10/22

**Comment by hakeemawbrey** [comment]
We launched @mospherepro - need to do a retrospect and find out where downloads came from and how many active people are their. 

Launched on
- Product hunt
- HTL
- Discord
- Twitter

**Comment by anthonyvprakash** [comment]
No further action needed here.
