### ISSUE TITLE
Identify New tool for Marketing

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#474]
Compare Marketing tools and find the best fit to the company

Ideas:

- [ ] [Notion](https://www.notion.so/feeb44f055de48ee9f6eaac42d434c00?v=97bc62da8411465ab041980aa2f0d394)
- [ ] [ClickUp](https://app.clickup.com/36193054/v/l/4-60119912-1)
  - [x] Pre-lim call scheduled with sales rep 5/20
  - [x] Demo of tool 6/1 - recording [here](https://drive.google.com/drive/folders/1J8SzJFdvMrhpAD9o622c07aGVvlASegv)
  - [ ] [Retrospective ](https://action.parabol.co/meet/dQ3NFK11v2/reflect)of how we want to move forward 6/2
- [ ] Trello
- [ ] Basecamp

**Comment by jenmonroe** [comment]
We're working in ClickUp but not everyone is happy with it. Planning to demo Notion next. Met with Opal, but not doing a trial as the cost is very high (over $12,000 per year).

**Comment by jenmonroe** [comment]
We had a late entry that appears to be the winner! [Google Tables](https://tables.area120.google.com/u/1/workspace/90xI9skmK2Edr1H8vNH4_K/table/9mWrUfyWMHmdgi-STZy_JG)
