### ISSUE TITLE
Flutter SV May Event - May 25

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#482]
- [x] Host and execute the event on May 25
- [x] F & B Logistics for the event
- [x] Plan for networking/learnings from last time
- [x] Recording and publishing on YT

**Comment by hakeemawbrey** [comment]
Videos are done https://www.youtube.com/playlist?list=PLkfwWUPYyMF3TUNlto7iApmns8XOdLAog

all thats left is the write up of post event

**Comment by anthonyvprakash** [comment]
Write up to be posted by @thenobleone14
