### ISSUE TITLE
Whitepapers

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#49]
Utilize current content to redraft

**Comment by hakeemawbrey** [comment]
https://docs.google.com/document/d/17Q2HGAqD6WWPRbgdQUPex_Ps0sNJQqGMQo4gcOsPurM/edit?hl=en&forcehl=1#heading=h.z6ne0og04bp5

Whitepaper 
From June 2020

**Comment by TylerTrott** [comment]
Whitepaper seems to be written and published on atsign.dev
