### ISSUE TITLE
Organize docs section with copy, code samples and examples

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#60]
Lead Anthony

Migration of content, dependent on Pub.dev gaps.  [Tied to Issue](https://github.com/atsign-foundation/atsign.dev/issues/59)
- [x] Complete framework and documentation for all sections under Functional Arch menu under Docs
- [x] On the Engg. stand ups point out to Dev teams about new issues that have been raised regarding missing documentation, examples and code

**Comment by ksanty** [comment]
@aannttoo who else would you recommend work on this task?
