### ISSUE TITLE
AtSign.Dev Messaging - Homepage

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#87]
Hakeem Lead **- This is only regarding homepage content**

- [x] Everyone contribute to the [Dev messaging ](https://docs.google.com/document/d/1RYKgMZtujO21Mo5OrY9WxdvxvFbniPRpvM5RSwm78Os/edit)jamboard output (all)
- [x] Create single narrative based on above @eskao654 
High level view of [the @ platform](https://docs.google.com/document/d/17PClBSTnaWJpBgsXEd8DaWD54wbi85QsRgGZSozJI7c/edit)
The features/differentiators/benefits of the @ platform

**Comment by hakeemawbrey** [comment]
Esther's write up of the narrative 
https://docs.google.com/document/d/18p_EzVTsn9oy8WJYirlSUl5jP8evMsN1k34rGt6kITU/edit
