### ISSUE TITLE
Create assets corresponding to new messaging for Homepage

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#88]
Rocky Lead

@aannttoo  thinks we may need up to 6 new graphics for the homepage.

**Comment by rtilney** [comment]
Staging: https://devstaging.atsign.wtf

- [ ] determine darker color for nav background (use reverse logo)
- [ ] home hero background image can be something more colorful (apps?)
- [ ] internal hero backgrounds 

Graphics needed (Landing)

- [ ] No Infrastructure needed
- [ ] Privacy built-in by Default
- [ ] Super Quick Onboarding
- [ ] Hear from our Developer community
- [ ] Check out the apps built on the @platform
- [ ] Want to talk to us?

1. FAQ Layout (includes multiple categories) - @TylerTrott  to provide [outline](https://docs.google.com/spreadsheets/d/1vtX9tVE5LNdn7na2g9IS81MU3II0M1mUEYgum4XGTvM/edit#gid=306632993)
2. Community (propose new layout - grid)
3. Showcase images for each
