### ISSUE TITLE
Up to date samples examples for everything

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atsign.dev#9]
- [ ] tied to releases in github

**Comment by tinashe404** [comment]
@TylerTrott @Intiserahmed I'll reach out on gchat so we can sync up on this

**Comment by ksanty** [comment]
@TylerTrott @Intiserahmed @tinashe404 please provide an update.  TY

**Comment by tinashe404** [comment]
@ksanty I started a document, listed all the samples/examples that we had on atsign.dev and we are checking if they are up to date or no longer relevant. This will be completed by Wednesday

**Comment by ksanty** [comment]
> @tinashe404  I started a document, listed all the samples/examples that we had on atsign.dev and we are checking if they are up to date or no longer relevant. This will be completed by Wednesday

Amazing.  TY!

**Comment by ksanty** [comment]
@tinashe404 please add the document here when ready.

**Comment by TylerTrott** [comment]
https://docs.google.com/spreadsheets/d/1r-zgcWoTPPFrcS1ksC5UG6zZGwN1UnAlKFUzg2Ei3LI/edit?usp=sharing @ksanty
